# syntax=docker/dockerfile:1

# ---- Stage 1: Single-page application build ----
FROM node:slim AS frontend-build
WORKDIR /build
COPY package.json package-lock.json* ./
RUN npm ci
COPY tsconfig.json vite.config.ts ./
COPY frontend/ ./frontend/
RUN npm run build

# ---- Stage 2: Python runtime ----
FROM python:3.11-slim AS runtime

# Deployment metadata: the single source of truth generated by
# scripts/generate_build_info.py in CI. Left at their defaults for local
# `docker build` runs, where the running app then reports "dev"/"unknown".
ARG APP_VERSION=dev
ARG GIT_COMMIT=unknown
ARG BUILD_TIME=unknown

LABEL org.opencontainers.image.version="${APP_VERSION}" \
      org.opencontainers.image.revision="${GIT_COMMIT}" \
      org.opencontainers.image.created="${BUILD_TIME}"

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get upgrade --yes \
    && rm -rf /var/lib/apt/lists/* \
    && python -m pip install --no-cache-dir --upgrade pip setuptools wheel \
    && groupadd --gid 10001 appuser \
    && useradd --uid 10001 --gid 10001 --shell /bin/false --no-create-home appuser

WORKDIR /app

COPY pyproject.toml ./
COPY app/ ./app/
COPY alembic/ ./alembic/
COPY alembic.ini ./
COPY scripts/entrypoint.sh scripts/assert_empty_e2e_database.py scripts/backup_database.py scripts/restore_database.py scripts/run_migrations.py scripts/validate_backup.py ./scripts/

COPY --from=frontend-build /build/app/static/dist ./app/static/dist

RUN printf '{"version": "%s", "commit": "%s", "build_time": "%s"}\n' \
      "$APP_VERSION" "$GIT_COMMIT" "$BUILD_TIME" > build_info.json \
    && pip install --no-cache-dir . \
    && python -m pip uninstall --yes pip setuptools wheel \
    && chmod +x scripts/entrypoint.sh \
    && mkdir -p /data \
    && chown -R 10001:10001 /app /data

VOLUME ["/data"]
EXPOSE 8000

USER 10001:10001

ENTRYPOINT ["scripts/entrypoint.sh"]
