image:
  repository: ghcr.io/vvojtisek/workout-logger
  tag: "feat-v2-initial-setup"
  pullPolicy: Always

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 10001
  runAsGroup: 10001
  fsGroup: 10001
  seccompProfile:
    type: RuntimeDefault

ingress:
  enabled: true
  className: "traefik"
  hosts:
    - host: workout-logger.local
      paths:
        - path: /
          pathType: Prefix

env:
  APP_ENV: development
  APP_VERSION: "2.0.0-dev"
  LOG_LEVEL: DEBUG
  TRUSTED_HOSTS: "localhost,127.0.0.1,workout-logger.local"
  PUBLIC_BASE_URL: "http://workout-logger.local"
  API_KEY: "dev-secret-key-12345-Camcorder-Sustainer9-Poem-Scarf-Drumstick"