"""initial schema

Revision ID: 93469c1ebbbf
Revises:
Create Date: 2026-07-17 21:10:04.708438

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.base


# revision identifiers, used by Alembic.
revision: str = "93469c1ebbbf"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workout_plans",
        sa.Column("name", sa.String(length=120, collation="NOCASE"), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", app.models.base.GUID(length=36), nullable=False),
        sa.Column("created_at", app.models.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", app.models.base.UTCDateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "plan_exercises",
        sa.Column("workout_plan_id", app.models.base.GUID(length=36), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("exercise_name", sa.String(length=150), nullable=False),
        sa.Column("target_sets", sa.Integer(), nullable=False),
        sa.Column("target_reps_min", sa.Integer(), nullable=False),
        sa.Column("target_reps_max", sa.Integer(), nullable=False),
        sa.Column("target_weight_kg", sa.REAL(), nullable=True),
        sa.Column("rest_time_seconds", sa.Integer(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", app.models.base.GUID(length=36), nullable=False),
        sa.CheckConstraint(
            "target_reps_max >= target_reps_min", name="ck_plan_exercise_reps_range"
        ),
        sa.ForeignKeyConstraint(["workout_plan_id"], ["workout_plans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workout_plan_id", "sort_order"),
    )
    op.create_index(
        "ix_plan_exercises_plan_order",
        "plan_exercises",
        ["workout_plan_id", "sort_order"],
        unique=False,
    )
    op.create_table(
        "workout_logs",
        sa.Column("source_plan_id", app.models.base.GUID(length=36), nullable=True),
        sa.Column("source_plan_name", sa.String(length=120), nullable=True),
        sa.Column("performed_at", app.models.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("total_time_minutes", sa.Integer(), nullable=False),
        sa.Column("calories_burned", sa.Integer(), nullable=True),
        sa.Column("overall_feeling", sa.Integer(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", app.models.base.GUID(length=36), nullable=False),
        sa.Column("created_at", app.models.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", app.models.base.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["source_plan_id"], ["workout_plans.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_workout_logs_performed_at", "workout_logs", ["performed_at"], unique=False)
    op.create_index(
        "ix_workout_logs_source_plan_id", "workout_logs", ["source_plan_id"], unique=False
    )
    op.create_table(
        "exercise_logs",
        sa.Column("workout_log_id", app.models.base.GUID(length=36), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("exercise_name", sa.String(length=150), nullable=False),
        sa.Column("sets_count", sa.Integer(), nullable=False),
        sa.Column("reps_per_set", sa.JSON(), nullable=False),
        sa.Column("weight_kg", sa.REAL(), nullable=True),
        sa.Column("rest_time_seconds", sa.Integer(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", app.models.base.GUID(length=36), nullable=False),
        sa.ForeignKeyConstraint(["workout_log_id"], ["workout_logs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workout_log_id", "sort_order"),
    )
    op.create_index(
        "ix_exercise_logs_log_order",
        "exercise_logs",
        ["workout_log_id", "sort_order"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_exercise_logs_log_order", table_name="exercise_logs")
    op.drop_table("exercise_logs")
    op.drop_index("ix_workout_logs_source_plan_id", table_name="workout_logs")
    op.drop_index("ix_workout_logs_performed_at", table_name="workout_logs")
    op.drop_table("workout_logs")
    op.drop_index("ix_plan_exercises_plan_order", table_name="plan_exercises")
    op.drop_table("plan_exercises")
    op.drop_table("workout_plans")
    # ### end Alembic commands ###
