---
image:
  repository: ghcr.io/vvojtisek/workout-logger
  tag: ""
  digest: "sha256:9715fd3c56b2270dbd6cd55c6530e13b57c2d9d6619dbd7bf82997be1ec7b8a3"
  sourceCommit: "f9d152b93854d5df6f9c5d886bac07a714f6ae65"
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  className: traefik
  hosts:
    - host: fitness.vvojtisek.eu
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: workout-logger-tls
      hosts:
        - fitness.vvojtisek.eu

env:
  APP_ENV: production
  APP_VERSION: "2.0.0"
  LOG_LEVEL: INFO
  TRUSTED_HOSTS: "localhost,127.0.0.1,fitness.vvojtisek.eu"
  PUBLIC_BASE_URL: "https://fitness.vvojtisek.eu/"

persistence:
  enabled: true
  size: 2Gi

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
