---
replicaCount: 1

strategy:
  type: Recreate

image:
  repository: ghcr.io/vvojtisek/workout-logger
  tag: ""
  digest: "sha256:437ef278f657981e69a0285d8909c62e87532cb126f5af8143a920edb2e529b7"
  sourceCommit: "c43975045a528810a3cf8d8109298011712be194"
  pullPolicy: IfNotPresent

existingSecret: workout-logger-secret
apiKeySecretKey: API_KEY

ingress:
  enabled: true
  className: traefik
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: fitness.vvojtisek.eu
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: workout-logger-tls
      hosts:
        - fitness.vvojtisek.eu

env:
  APP_ENV: production
  APP_VERSION: "2.0.0"
  LOG_LEVEL: INFO
  TRUSTED_HOSTS: "localhost,127.0.0.1,fitness.vvojtisek.eu"
  PUBLIC_BASE_URL: "https://fitness.vvojtisek.eu/"
  RUN_MIGRATIONS_ON_STARTUP: "false"

persistence:
  enabled: true
  size: 2Gi

backupPersistence:
  enabled: true
  size: 2Gi

backup:
  enabled: true
  schedule: "17 2 * * *"
  keep: 7

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
